import { Router } from "express";
import { approvePlan, createOrRegeneratePlan, createResearchJob, executeApprovedWorkflow, getResearchJob, listResearchJobs, passthroughWorkflowStep, reviewEvidence } from "../controllers/research.controller.js";
import { requireAuth, requireRole } from "../middleware/auth.middleware.js";
import { feedback } from "../controllers/report.controller.js";

const router = Router();
router.use(requireAuth);
router.post("/research-jobs", createResearchJob);
router.get("/research-jobs", listResearchJobs);
router.get("/research-jobs/:id", getResearchJob);
router.post("/research-plan", createOrRegeneratePlan);
router.post("/research-jobs/:jobId/approve-plan", approvePlan);
router.post("/research-jobs/:jobId/run", executeApprovedWorkflow);
router.post("/browse", passthroughWorkflowStep);
router.post("/extract", passthroughWorkflowStep);
router.post("/validate", passthroughWorkflowStep);
router.post("/aggregate", passthroughWorkflowStep);
router.post("/generate-report", passthroughWorkflowStep);
router.post("/feedback", feedback);
router.patch("/evidence/:id/review", requireRole("reviewer", "admin"), reviewEvidence);
export default router;
